package dev.gavinfecko.triagedesk.identity;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import dev.gavinfecko.triagedesk.common.security.JwtConfig;
import dev.gavinfecko.triagedesk.common.security.JwtProperties;
import java.security.KeyPairGenerator;
import java.time.Duration;
import java.time.Instant;
import java.util.Base64;
import org.junit.jupiter.api.Test;
import org.springframework.security.oauth2.jwt.JwsHeader;
import org.springframework.security.oauth2.jwt.JwtClaimsSet;
import org.springframework.security.oauth2.jwt.JwtEncoderParameters;

class JwtKeysTest {

    // Assembled at runtime around a key generated by the test, so no key-shaped literal sits in the source.
    private static final String PEM_DASHES = "-----";
    private static final String PEM_LABEL = "PRIVATE KEY";

    static JwtProperties props(String secret, String privateKey) {
        return new JwtProperties("triagedesk", secret, privateKey, Duration.ofMinutes(15), Duration.ofDays(7));
    }

    @Test
    void rs256FromAPkcs8PemSignsTokensItsOwnDecoderAccepts() throws Exception {
        var generator = KeyPairGenerator.getInstance("RSA");
        generator.initialize(2048);
        var pair = generator.generateKeyPair();
        String pem = PEM_DASHES + "BEGIN " + PEM_LABEL + PEM_DASHES + "\n"
                + Base64.getMimeEncoder().encodeToString(pair.getPrivate().getEncoded())
                + "\n" + PEM_DASHES + "END " + PEM_LABEL + PEM_DASHES + "\n";
        JwtConfig.Keys keys = JwtConfig.Keys.from(props(null, pem));
        JwtConfig.Signing signing = keys.signing();
        assertThat(signing.algorithm().getName()).isEqualTo("RS256");
        Instant now = Instant.now();
        String token = signing.encoder()
                .encode(JwtEncoderParameters.from(
                        JwsHeader.with(signing.algorithm()).build(),
                        JwtClaimsSet.builder()
                                .subject("x")
                                .issuedAt(now)
                                .expiresAt(now.plusSeconds(60))
                                .build()))
                .getTokenValue();
        assertThat(keys.decoder().decode(token).getSubject()).isEqualTo("x");
    }

    @Test
    void privateKeyWinsOverSecretAndGarbageKeysFailFast() {
        assertThatThrownBy(() -> JwtConfig.Keys.from(props("long-enough-secret-long-enough-secret!", "not a key")))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("PKCS#8");
    }

    @Test
    void noKeyOrAShortSecretStopsStartup() {
        assertThatThrownBy(() -> JwtConfig.Keys.from(props(null, " "))).hasMessageContaining("No JWT signing key");
        assertThatThrownBy(() -> JwtConfig.Keys.from(props("too-short", null))).hasMessageContaining("32 bytes");
    }
}
