-- V10 (TD-33): full-text search over title and description. The vector is generated by the
-- database, so it can never drift from the text, and the two SQL functions let the ORM's criteria
-- queries use it; PostgreSQL inlines them, so the GIN index still applies.
ALTER TABLE tickets
    ADD COLUMN search_vector tsvector
        GENERATED ALWAYS AS (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(description, ''))) STORED;

CREATE INDEX tickets_search_idx ON tickets USING gin (search_vector);

CREATE FUNCTION ticket_matches(v tsvector, words text) RETURNS boolean
    LANGUAGE sql STABLE AS $$ SELECT v @@ plainto_tsquery('english', words) $$;

CREATE FUNCTION ticket_rank(v tsvector, words text) RETURNS real
    LANGUAGE sql STABLE AS $$ SELECT ts_rank(v, plainto_tsquery('english', words)) $$;
